plugins {
    id 'com.android.application' version '8.2.2'
}

android {
    namespace 'com.custom.webwallpaper'
    compileSdk 34

    defaultConfig {
        applicationId "com.custom.webwallpaper"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
