name: Build Android APK
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Install Cordova
        run: npm install -g cordova
      - name: Build APK
        run: |
          export CI=true
          export CORDOVA_NO_TELEMETRY=1
          export CORDOVA_ANDROID_GRADLE_DISTRIBUTION_URL=https\://services.gradle.org/distributions/gradle-8.7-all.zip
          cd /tmp
          cordova create app com.custom.webwallpaper482720 "Wallpaper" --no-telemetry
          rm -rf app/www/*
          cp -R $GITHUB_WORKSPACE/* app/www/ || true
          cd app
          sed -i 's/version="1.0.0"/version="1.0.0"/g' config.xml
          sed -i 's/<\/widget>/\n    <allow-navigation href="*" \/>\n    <allow-intent href="*" \/>\n<\/widget>/g' config.xml
          sed -i 's/<\/widget>/\n    <icon src="icon.png" \/>\n<\/widget>/g' config.xml
          cordova plugin add cordova-plugin-inappbrowser --no-telemetry || true
          cordova platform add android@13.0.0 --no-telemetry
          cordova build android --no-telemetry
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: /tmp/app/platforms/android/app/build/outputs/apk/debug/app-debug.apk